todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/webapp/urls.py
from django.urls import path
from webapp.views import TaskView, CreateTask, UpdateTask, DeleteTask, IndexView, ProjectIndexView, CreateProject, ProjectView, ProjectDelete, ProjectUpdate, ProjectUserUpdate
from django.views.generic import RedirectView


app_name = 'webapp'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='webapp:index')),
    path('task/', IndexView.as_view(), name='index'),
    path('task/create/', CreateTask.as_view(), name='create_task'),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('task/<int:pk>/update/', UpdateTask.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', DeleteTask.as_view(), name='task_delete'),
    path('project/', ProjectIndexView.as_view(), name='project_index'),
    path('project/create/', CreateProject.as_view(), name='create_project'),
    path('project/view/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/<int:pk>/update/', ProjectUpdate.as_view(), name='project_update'),
    path('rpoject/<int:pk>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('project/<int:pk>/userupdate/', ProjectUserUpdate.as_view(), name='project_userupdate'),
]

todolist/webapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model


class ProjectTask(models.Model):
    name = models.CharField(max_length=25, verbose_name = 'Название')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    start_date = models.DateField(default=timezone.now, verbose_name='Дата начала')
    end_date = models.DateField(null=True, blank=True, verbose_name='Дата окончания')
    user = models.ManyToManyField(get_user_model(), related_name='projecttasks', verbose_name='Пользователь')

    class Meta:
        permissions = [
            ('сan_add_user', 'Может добавлять пользователя'),
            ('сan_change_user', 'Может изменять пользователя'),
            ('сan_delete_user', 'Может удалять пользователя'),
        ]

    def __str__(self):
        return f"{self.pk}. {self.name}"


class TypeTask(models.Model):
    title = models.CharField(max_length=25, verbose_name='Название')

    def __str__(self):
        return f"{self.pk}. {self.title}"


class StatusTask(models.Model):
    title = models.CharField(max_length=25, verbose_name='Название')

    def __str__(self):
        return f"{self.pk}. {self.title}"


class Task(models.Model):
    summary = models.CharField(max_length=60, verbose_name='Краткое описание')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name="Полное описание")
    project_task = models.ForeignKey("webapp.ProjectTask", verbose_name=("Проект"), related_name='tasks', on_delete=models.CASCADE)
    status = models.ForeignKey('webapp.StatusTask', on_delete=models.PROTECT, related_name='tasks', verbose_name='Статус')
    type_task = models.ManyToManyField('webapp.TypeTask', related_name='tasks', blank=True)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    update_time = models.DateTimeField(auto_now=True, verbose_name='Время обновления')

    def __str__(self):
        return f"{self.pk}. {self.summary[:15]}"

todolist/webapp/forms.py
from django import forms
from django.forms import widgets, ValidationError
from webapp.models import Task, ProjectTask
from django.contrib.auth import get_user_model

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['summary', 'description', 'project_task', 'status', 'type_task']
        widgets = {'type_task': widgets.CheckboxSelectMultiple}

    def clean_summary(self):
        summary = self.cleaned_data['summary']
        bans = ['test_1', 'test_2', "test_3"]
        if len(summary) < 5:
            self.add_error('summary', ValidationError('Длина поля должна составлять не меенее %(length)d символов!', code='too_short', params={'length': 5}))
        elif len(summary) > 50:
            self.add_error('summary', ValidationError('Длина поля должна составлять не более %(length)d символов!', code='too_long', params={'length': 50}))
        for ban in bans:
            if summary == ban:
                self.add_error('summary', ValidationError("Эти слова запрешено вводить!"))
        return summary

    def clean_description(self):
        description = self.cleaned_data['description']
        bans = ['test_1', 'test_2', "test_3"]
        for ban in bans:
            for desc in description.split():
                if desc == ban:
                    self.add_error('summary', ValidationError("Эти слова запрешено вводить!"))
        if len(description) < 10:
            self.add_error('description', ValidationError('Длина поля должна составлять не меенее %(length)d символов!', code='too_short', params={'length': 30}))
        return description


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=40, required=False, label='Найти')

class ProjectTaskForm(forms.ModelForm):
    class Meta:
        model = ProjectTask
        fields = ['name', 'description', 'start_date', 'end_date']



class ProjectUserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = get_user_model().objects.exclude(pk=self.user.pk)
    class Meta:
        model = ProjectTask
        fields = ['user']
        widgets = {'user': widgets.CheckboxSelectMultiple}

    def save(self, commit=True):
        projecttask = super().save(commit=commit)

        if commit:
            projecttask.user.add(self.user)
            projecttask.save()

        return projecttask

todolist/webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.utils.http import urlencode
from django.db.models import Q
from webapp.models import Task
from webapp.forms import TaskForm, SimpleSearchForm
from django.views.generic import TemplateView, View, FormView, ListView


class IndexView(ListView):
    template_name = 'tasks/index.html'
    context_object_name = 'tasks'
    model = Task
    ordering = ('create_time', 'update_time',)
    paginate_by = 10
    

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class TaskView(TemplateView):
    template_name = 'tasks/task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["task"] = get_object_or_404(Task, pk=kwargs['pk'])
        return context


class CreateTask(FormView):
    template_name = 'tasks/create.html'
    form_class = TaskForm

    def get_success_url(self):
        return reverse('task_view', kwargs={'pk': self.task.pk})
    
    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)


class UpdateTask(FormView):

    template_name = "tasks/task_update.html"
    form_class = TaskForm

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Task, pk=pk)

    def dispatch(self, request, *args, **kwargs):
        self.task = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.task
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.task
        return kwargs

    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task_view', kwargs={'pk': self.task.pk})


class DeleteTask(View):
    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs['pk'])
        return render(request, 'tasks/task_delete.html', {'task': task})

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs['pk'])
        task.delete()
        return redirect('index')

todolist/webapp/views/project_views.py
from django.shortcuts import reverse, redirect
from django.core.paginator import Paginator
from webapp.models import ProjectTask
from webapp.forms import ProjectTaskForm, ProjectUserForm
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

class ProjectIndexView(ListView):
    template_name = 'project/project_index.html'
    context_object_name = 'projects'
    model = ProjectTask
    ordering = '-start_date' 


class ProjectView(LoginRequiredMixin, DetailView):
    template_name = 'project/project_view.html'
    model = ProjectTask


    def get_context_data(self, **kwargs):

        tasks = self.object.tasks.all()
        paginator = Paginator(tasks, 3)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = super().get_context_data(**kwargs)
        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        context['tasks'] = page_obj.object_list
        return context


class CreateProject(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    model = ProjectTask
    form_class = ProjectTaskForm
    permission_required = 'webapp.add_projecttask'


    def form_valid(self, form):
        self.object = form.save()
        self.object.user.add(self.request.user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})




class ProjectDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'project/project_delete.html'
    model = ProjectTask
    context_object_name = 'project'
    success_url = reverse_lazy('webapp:project_index')
    permission_required = 'webapp.delete_projecttask'

    def test_func(self):
        return self.get_object().user in self.request.user and self.request.user.has_perm('webapp.delete_projecttask')


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    template_name = "project/project_update.html"
    form_class = ProjectTaskForm
    model = ProjectTask
    permission_required = 'webapp.change_projecttask'

    def test_func(self):
        return self.get_object().user in self.request.user and self.request.user.has_perm('webapp.change_projecttask')

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectUserUpdate(PermissionRequiredMixin, UpdateView):
    model = ProjectTask
    form_class = ProjectUserForm
    template_name = "project/project_user.html"
    permission_required = 'webapp.сan_add_user'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().user.all()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

todolist/webapp/views/task_views.py
from django.shortcuts import get_object_or_404, reverse
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.db.models import Q
from webapp.models import Task, ProjectTask
from webapp.forms import TaskForm, SimpleSearchForm
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class IndexView(ListView):
    template_name = 'tasks/index.html'
    context_object_name = 'tasks'
    model = Task
    ordering = ('create_time', 'update_time',)
    paginate_by = 10
    

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class TaskView(LoginRequiredMixin, TemplateView):
    template_name = 'tasks/task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["task"] = get_object_or_404(Task, pk=kwargs['pk'])
        return context


class CreateTask(PermissionRequiredMixin, CreateView):
    template_name = 'tasks/create.html'
    form_class = TaskForm
    model = Task
    permission_required = 'webapp.add_task'



    def form_valid(self, form):
        form.instance.projecttask = get_object_or_404(ProjectTask, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.projecttask.pk})


class UpdateTask(PermissionRequiredMixin, UpdateView):

    template_name = "tasks/task_update.html"
    form_class = TaskForm
    model = Task
    permission_required = 'webapp.change_task'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().projecttask.user.all()

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.projecttask.pk})


class DeleteTask(PermissionRequiredMixin, DeleteView):
    template_name = 'tasks/task_delete.html'
    model = Task
    permission_required = 'webapp.delete_task'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().projecttask.user.all()

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.projecttask.pk})

todolist/webapp/templates/tasks/create.html
{% extends "base.html" %}

{% block title %}Создать задачу{% endblock %}

    {% block nav %}
    <li class="nav-item">

    </li>
    {% endblock %}

    {% block content %}
        <h2>Создать задачу</h2>
        <form action="" method="POST">
            {% include "partial/form.html" with button_text="Создать" %}
        </form>
    {% endblock %}

todolist/webapp/templates/tasks/index.html
{% extends "base.html" %}

{% block title %}Главная страница{% endblock %}

{% block nav %}
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        
        <a class="nav-link" href="{% url 'webapp:create_task' %}">Новая задача</a>
        
    </li>
    {% endif %}
    {% include "partial/simple_search.html" %}
{% endblock %}


    {% block content %}
    <h1>To Do List</h1>
    <div class="row">
        {% for task in tasks %}
            <div class="col-auto">
                <div class="card col">
                    <h5 class="card-header">Название: <a href="{% url 'webapp:task_view' task.pk %}">{{ task.summary }}</a></h5>
                    <div class="card-body">
                        <h5 class="card-title">Статус: {{ task.status.title }}</h5>
                        <p>Тип: {% for type in task.type_task.all %}
                            {{type.title}} {% if not forloop.last %},{% endif%}
                            {% endfor %}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>  
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    
    {% endblock %}

todolist/webapp/templates/tasks/task_delete.html
{% extends "base.html" %}

{% block title %}Удаление задачи{% endblock %}

{% block nav %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:task_view' task.pk %}">Просмотр задачи</a>
</li>
{% endblock %}

{% block content %}
    <h4>Вы уверены что хотите удалить "{{ task.summary }}"?</h4>
    <form method="POST" action="{% url "webapp:task_delete" task.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Потверждение"></p>
        <p><a href="{% url "webapp:task_view" task.pk %}">Отмена</a></p>
    </form>
{% endblock %}

todolist/webapp/templates/tasks/task_update.html
{% extends "base.html" %}

{% block title %}Редактирование задачи{% endblock %}

{% block nav %}
<li class="nav-item">

</li>
{% endblock %}

    {% block content %}
        <h2>Обновить задачу</h2>
        <form action="" method="POST">
            {% include "partial/form.html" with button_text="Обновить" %}
        </form>
    {% endblock %}

todolist/webapp/templates/tasks/task_view.html
{% extends "base.html" %}

{% block title %}Просмотр задачи{% endblock %}

{% block nav %}
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        {% if perms.webapp.add_task or projecttask.user == request.user %}
        <a class="nav-link" href="{% url 'webapp:create_task' %}">Новая задача</a>
        {% endif %}
    </li>

    <li class="nav-item">
        {% if perms.webapp.delete_task or projecttask.user == request.user %}
        <a class="nav-link" href="{% url 'webapp:task_delete' task.pk %}">Удалить</a>
        {% endif %}
    </li>
    {% endif %}
{% endblock %}

    {% block content %}
        <div class="card text-center">
            <div class="card-header">
                Название: {{ task.summary }}
            </div>
            <div class="card-body">
                <p class="card-text" style="white-space: pre-wrap">Подродное описание: {{ task.description }}</p>
                {% if request.user.is_authenticated and perms.webapp.delete_task or projecttask.user == request.user %}
                <a href="{% url 'webapp:task_update' task.pk %}" class="btn btn-primary">Обновление</a>
                {% endif %}
            </div>
            <div class="card-footer text-muted">
                <p>Статус: {{ task.status.title }}</p>

                <p>Тип: {% for type in task.type_task.all %}
                    {{type.title}} {% if not forloop.last %},{% endif%}
                {% endfor %}</p>
            </div>
        </div>
    {% endblock %}