todolist/accounts/urls.py
from django.urls import path
from accounts.views import RegisterView, UserDetailView, UsersView, UserChangeView, UserPasswordChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('users/', UsersView.as_view(), name='users_list'),
    path('change/',  UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/webapp/urls.py
from django.urls import path
from webapp.views import TaskView, CreateTask, UpdateTask, DeleteTask, IndexView, ProjectIndexView, CreateProject, ProjectView, ProjectDelete, ProjectUpdate, ProjectUserUpdate
from django.views.generic import RedirectView


app_name = 'webapp'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='webapp:index')),
    path('task/', IndexView.as_view(), name='index'),
    path('task/create/', CreateTask.as_view(), name='create_task'),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('task/<int:pk>/update/', UpdateTask.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', DeleteTask.as_view(), name='task_delete'),
    path('project/', ProjectIndexView.as_view(), name='project_index'),
    path('project/create/', CreateProject.as_view(), name='create_project'),
    path('project/view/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/<int:pk>/update/', ProjectUpdate.as_view(), name='project_update'),
    path('rpoject/<int:pk>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('project/<int:pk>/userupdate/', ProjectUserUpdate.as_view(), name='project_userupdate'),
]

todolist/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_avatar', verbose_name='Аватар')
    social_github = models.URLField(max_length=500, null=True, blank=True, verbose_name='Ссылка')
    about_me = models.TextField(max_length=3000, null=True, blank=True, verbose_name="О себе")

    def __str__(self):
        return f"{self.user.username} 's Profile"

    class Meta:
        db_table = 'profile'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

todolist/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError
from django.contrib.auth import get_user_model
from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        if email == '':
            self.add_error('email', ValidationError('Почта обязательно к заполнению', code='error_email'))
        return email


    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        if first_name == '':
            if last_name == '':
                raise forms.ValidationError('Заполните Имя или Фамилию!', code='error_first_last_name')

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'social_github', 'about_me']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

todolist/accounts/views.py
from django.shortcuts import redirect
from django.contrib.auth import login
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.urls import reverse
from accounts.models import Profile
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.list import MultipleObjectMixin
from django.contrib.auth.views import PasswordChangeView

# Create your views here.

class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'user_registration.html'

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        next_url = self.request.POST.get('next')
        if next_url:
            return next_url
        return reverse('webapp:index')


class UserDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        projects = self.get_object().projecttasks.all()
        return super().get_context_data(object_list=projects, **kwargs)



class UsersView(PermissionRequiredMixin, ListView):
    template_name = 'users.html'
    context_object_name = 'users_list'
    model = get_user_model() 
    paginate_by = 3
    permission_required = 'accounts.view_profile'



class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'
    form_profile_class = ProfileChangeForm



    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'profile_form' not in kwargs:
            context['profile_form'] = self.form_profile_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.form_profile_class(instance=self.get_object().profile, data=request.POST, files=request.FILES)
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.get_object().pk})


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'user_pass_change.html'

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.request.user.pk})

todolist/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Вход</h1>
    <form action="" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>

{% endblock %}

todolist/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block content %}
    <h1>Поменять личные данные</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with fields_only=True %}
        {% include 'partial/form.html' with form=profile_form button_text="Изменить"%}

    </form>
{% endblock %}

todolist/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block nav %}
    {% if user_obj.pk == request.user.pk %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change' %}">Редактировать </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:password_change' %}">Смена пароля</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>

    <div class="card mb-3">
        <div class="row g-0">
            {% if user_obj.profile.avatar %}
                <div class="col-md-4">
                    <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid rounded-start w-75">
                </div>
            {% endif %}
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
                    <p class="card-text">Имя: {{ user_obj.first_name }}</p>
                    <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
                    <p class="card-text">Ссылка на гитхаб: <a href="{{ user_obj.profile.social_github }}">{{ user_obj.profile.social_github }}</a></p>
                    <p class="card-text">О себе: {{ user_obj.profile.about_me }}</p>
                </div>
            </div>
        </div>
    </div>

    {% include 'partial/project_partial.html' with projects=object_list %}
{% endblock %}

todolist/accounts/templates/user_pass_change.html
{% extends 'base.html' %}
{% block content %}
    <h1>Смена пароля</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Изменить" %}

    </form>
{% endblock %}

todolist/accounts/templates/user_registration.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}

    {% block nav %}
    <li class="nav-item">

    </li>
    {% endblock %}

    {% block content %}
        <h2>Регистрация</h2>
        <form action="" method="POST">
            {% include "partial/form.html" with button_text="Регистрация" %}
        </form>
    {% endblock %}

todolist/accounts/templates/users.html
{% extends 'base.html' %}


{% block content %}
<ul class="list-group">
    {% if perms.accounts.view_profile %}
    {% for user in users_list %}

        <li class="list-group-item"><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></li>

    {% endfor %}
    {% endif %}
</ul>
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}
{% endblock %}


{% url 'accounts:detail' user.pk %}